# Generated by Django 3.0.2 on 2020-01-24 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(help_text='enter your student id here', max_length=6, null=True)),
                ('year_of_graduation', models.IntegerField()),
                ('date_of_birth', models.IntegerField()),
                ('technical_program', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('apt', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('company_adddress', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('wage', models.IntegerField(blank=True, default=0, null=True)),
                ('college_acceptance_letter', models.FileField(blank=True, null=True, upload_to='')),
                ('college_attend', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('college_year_lenght', models.IntegerField(help_text='enter your student id here', null=True)),
                ('military_branch', models.CharField(default='none', max_length=255, null=True)),
                ('military_letter', models.FileField(blank=True, null=True, upload_to='')),
                ('A_adams_scholarship', models.BooleanField(default=False, null=True)),
                ('technical_certification', models.CharField(blank=True, default='none', help_text='enter your student id here', max_length=255, null=True)),
                ('osha_training', models.BooleanField(null=True)),
                ('osha_number', models.IntegerField(blank=True, null=True)),
                ('WTHS_certification', models.CharField(blank=True, help_text='enter your student id here', max_length=255, null=True)),
                ('future_plans', models.TextField(help_text='what are your future plans', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
