# Generated by Django 3.0.2 on 2020-02-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslip', '0002_auto_20200124_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
