# Generated by Django 3.0.2 on 2020-02-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslip', '0003_auto_20200226_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company_adddress',
            new_name='company_address',
        ),
    ]
