# Generated by Django 3.0.2 on 2020-02-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslip', '0004_auto_20200226_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='college_year_lenght',
            new_name='college_major',
        ),
        migrations.AddField(
            model_name='profile',
            name='college_year_length',
            field=models.IntegerField(help_text='enter your student id here', null=True),
        ),
    ]
