# Generated by Django 3.0.3 on 2020-03-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslip', '0005_auto_20200226_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college_major',
            field=models.CharField(help_text='enter your student id here', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='osha_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(max_length=255),
        ),
    ]
